name: Build and deploy JAR app to Azure Web App - spring-ai-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Java 17 using Microsoft's distribution
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Grant execute permissions to the Gradle wrapper script
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Upload the built JAR file as an artifact for the deploy job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Azure Login Step with OIDC
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscription: true

      # Deploy the JAR to Azure Web App using the publish profile
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'spring-ai-backend'
          slot-name: 'Production'
          package: 'build/libs/*.jar'
          publish-profile: ${{ secrets.Azure_API_Key }}
